services:
  - type: web
    name: crypto-tracker
    env: python
    pythonVersion: '3.10'
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --preload app:app"
    disks:
      - name: data
        mountPath: /data
        sizeGB: 1
